name: Pull Request Emoji Check

on:
  # Trigger the workflow on pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master

jobs:
  title:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Check for Emoji
        uses: neofinancial/ticket-check-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          titleRegex: '/^:bug:|:seedling:|:ghost:|:book:|:sparkles:|:warning:/'