name: "PR Title Checker"
on:
  # Trigger the workflow on pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses = "./../../scripts/ci"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        #  pattern: '/^:bug:|:seedling:|:ghost:|:book:|:sparkles:|:warning:/'

